### PR TITLE
Moved method_matches_args to ObjectDispatch instance method

### PR DESCRIPTION
**Pull request by Amwam**

### CODE REVIEW

**Comment by percious** [comment]
I don't think this is a good idea.

method_matches_args should remain a function because it can be used within a dispatcher at a different level of abstraction.  Limiting this capability to ObjectDispatch would be short-sighted at best.

What is broken that you are trying to fix?

**Comment by Amwam** [comment]
We wanted to do some transformations on request arguments, before they reach the actual method, while still needing to know which method they were intended for. 
To simplify thing, we moved the `method_matches_args` into the dispatcher, so it could be overridden by our own controllers.

for example our case would be like so;
Method may be of the form `foo(var1, var2)` and the request was `/foo?id_for_var1=x&var2=y`, we wanted to transform `id_for_var1` into a different object (`var1`).

**Comment by percious** [comment]
It sounds like what you need to do is use the @validate decorator on your foo function to convert the var into an object.  This would be the standard TG way to solve this problem.

see: http://turbogears.readthedocs.org/en/latest/turbogears/validation.html#writing-custom-validators

**Comment by Amwam** [comment]
I'm not sure it fits, there is no way with validation (that I can see) to be able to change one parameter into another. While we can do the actual lookup, the dispatch fails to find the method, as the arguments it accepts are different to the ones sent.
For our case, we send `my_object_id` to the server, and then we want to inject the actual instance into the method to use, but have that called as `my_object`.

Do you have any other suggestions?

**Comment by percious** [comment]
yes, you can change the function signature of foo() to match what your parameters say, or, better, change your URL schema.

**Comment by percious** [comment]
one other option is to extend AbstractDispatcher and provide your own _dispatch method that call self._method_matches_args to that end.  This would be the proper way to extend the TurboGears dispatch system to your heart's desire.  I think it's overkill for what you are trying to do, but you _can_ do it.   I'm sorry, but I don't think this change should be added to the framework, so I am closing.

**Comment by amol-** [comment]
I think that, while the solution is not very good (overriding `_method_matches_args`, which I actually consider an implementation detail that users should not need to know it exists), the use case makes sense.

If you want for example to "alias" a parameter (receiving both `user=` and `user_id=` should go to the same route) it's not achievable through validation because is executed after it already got dispatched and so you won't even reach the validation itself unless your method uses `**kwargs` which is not very elegant.

I faced a similar issue when working on an experimental port of Kallithea from Pylons to TG. To dispatch things I wanted to rely on `_lookup` which would return right **controller** and **action** where to continue dispatch. The issue I faced was that parameters had nothing to do with method arguments and so TG dispatch lead to 404 for every action implemented by a method with arguments and there was no way to adapt arguments before letting the dispatch continue.

I ended up working around the issue by throwing away always the keyword arguments in `_call` ( https://bitbucket.org/_amol_/kallithea-tg/src/34c2bc4ff4b5f83417ebb348a3723f4a566b7291/kallithea/lib/base.py?at=default&fileviewer=file-view-default#base.py-464:465 ) and then relying on `_lookup` `remainder` to pass all arguments by position ( https://bitbucket.org/_amol_/kallithea-tg/src/34c2bc4ff4b5f83417ebb348a3723f4a566b7291/kallithea/controllers/root.py?at=default&fileviewer=file-view-default#root.py-35:43 )

If there was a clear API to modify arguments during dispatch it would probably solve both @Amwam and my use cases. While touching `_method_matches_args` is not the right way to achieve this we should probably think of away to allow adapting arguments without having to rewrite the whole dispatch phase. In my case for example `_lookup` would be greatly improved by allowing to give back not only remainder but also keyword arguments.

**Comment by bertildaniel** [comment]
@percious There's a comment in the docstring suggesting that the method_args_vars is likely part of the ObjectDispatcher? Are there any use cases you are thinking of where the function is useful on its own - it could be left in-situ and attribute/hook could be added to ObjectDispatcher to allows us to override. The only other option available was to copy the dispatch code and most of the method_matches_args code into our own code as there was no way to hook into the chain.

@amol- It would be great to have a proper API for mangling of arguments, and of course preferable to more low-level tampering. Our approach here was to make a minimal change to allow us to extend ObjectDispatcher instead of rewriting. How would you see that working, i.e. where in the dispatch chain should that be inserted I guess before `method_matches_args`. If there's an agreeable plan we can attempt to adapt our fork to implement that.

**Comment by amol-** [comment]
@bertildaniel what you want to achieve can now easily be done by adding a default value to the new parameter that the function expects in TG2.3.8

For example, if you want to have `?user_name=value` appear into the `user` parameter you would just do:

```
def replace_user_name_with_user(remainder, params):
   params['user'] = params.get('user_name')

@before_validate(replace_user_name_with_user)
def myaction(self, user=None):
   return str(user)
```

Then the dispatcher would have no problems with the missing user argument as it has a default value and  you would rename the parameter before it gets validated or used.

On TG2.3.7 and before you could do the same, but just needed to add `**kwargs` to your action method.
That's actually done often by tgext.crud through `@map_primary_keys` and `@apply_default_filters` decorators https://github.com/TurboGears/tgext.crud/blob/master/tgext/crud/controller.py#L464

**Comment by amol-** [comment]
@bertildaniel also if you want to have a look at code that pretty much provides custom dispatching you can have a look at https://github.com/TurboGears/tgext.routes 

Regarding your question where to edit parameters you probably can do that in `_visit` Dispatching Entry Point ( http://turbogears.readthedocs.org/en/latest/turbogears/objectdispatch.html#dispatching-entry-points ) which is executed when you get to the controller but not yet to the action. There you can probably use `set_params` to change them on `tg.request.dispatch_state`

**Pull request closed without merging**
